version: '3.7'
services:
  nginx:
    container_name: "$PROXY_NAME"
    build:
      context: .
      args:
        certbot: $LETSENCRYPT_ENABLE
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - LETSENCRYPT_ENABLE
      - LETSENCRYPT_EMAIL
      - LOGROTATE_ENABLE
      - SELFSSL_COUNTRY
      - SELFSSL_STATE
      - SELFSSL_LOCALITY
      - SELFSSL_ORG
      - SELFSSL_OUN
      - SELFSSL_CN
      - SELFSSL_EMAIL
    volumes:
      - ./volumes/certs:/etc/ssl/nginx
      - ./volumes/letsencrypt/conf:/etc/letsencrypt
      - ./volumes/letsencrypt/log:/var/log/letsencrypt
      - ./volumes/nginx/conf:/etc/nginx/conf.d
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/nginx/html:/etc/nginx/html
    networks:
      - "$PROXY_NETWORK"

networks:
  proxy:
    name: "$PROXY_NETWORK"
