version: '3.7'
services:
  nginx:
    container_name: "$PROXY_NAME"
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/certs:/etc/ssl/nginx
      - ./volumes/letsencrypt/conf:/etc/letsencrypt
      - ./volumes/letsencrypt/log:/var/log/letsencrypt
      - ./volumes/nginx/conf:/etc/nginx/conf.d
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/nginx/html:/etc/nginx/html
    networks:
      - "$PROXY_NETWORK"

networks:
  proxy:
    name: "$PROXY_NETWORK"
